# Proposal

## Research topic

S&P 500 Index is a market-capitalization-weighted index of many of the largest US stocks.  As it covers over 80% the market capitalization of the US market, it is widely considered to represent the US market in the global financial asset allocators.  As a result, the E-Mini S&P 500 Futures is also one of the most commonly used futures for investors and traders to gain exposure to the US market.  Most commonly referred as ES futures, it is available for trading each week from each 6pm ET Sunday to 5pm ET Friday (including a short halt each day from 4:15-4:30pm and 5pm to 6pm).
Source: https://www.thebalancemoney.com/profile-of-the-sandp-500-es-futures-market-1031271

Anecdotally, we have observed that on some Fridays, the ES futures exhibit very strong returns in the final 30 minutes heading into the week's 5pm close, in a way that may indicate a short squeeze.  A short squeeze is when a surge of the market cover shorted stocks pushes the price of a stock up in a parabolic way.  The topic we want to explore in this project is to examine if this is a regular occurrence.  We will study if this pattern appears conditional on previous S&P 500 market return conditions, market's valuation, future's daily trading volume, net positioning, as well as level of market volatility and investor sentiment.  In addition, we will examine if a market return profile is conditional on potential market moving macro-economic events such as rate hikes from the Federal Reserve, or announcements of economic data such as ISM Manufacturing Index. 

## Data availability

In order to investigate the return behavior the E-mini S&P 500 futures and the market conditions, we need historical pricing, volume data, and many market and sentiment indicators.  Bloomberg Terminal is the application used by many professionals in the financial industry.  It aggregates and distributes market data, news, among many things, and is valuable resource for us to retrieve market related data in our project.

We plan to use Bloomberg Terminal accessible through the University's Library Terminals, to download pricing and volume data for E-mini S&P 500 futures.  Bloomberg has various access methods to its data, and we intend on using BDH function calls to pull "Bloomberg Data History".  We anticipate to use Excel to call for the necessary historical data, as such data will be downloaded into a spreadsheet format.

1. E-mini S&P 500 Futures

The E-mini S&P 500 futures identifier is ES1 Index, the Generic ES future security that Bloomberg tracks and will provide continuous pricing going back in history.  Bloomberg will only provide 140 days of historical intraday prices when downloading from Excel, and 240 days of intraday prices from the Terminal.  That is, if today is October 30, 2022, only prices up to 240 days ago is available from the Terminal.  This will limit our study to approximately the past 1 year of trading days.

Pricing and volume

The data fields we intend on accessing include the following, using the respective Bloomberg codes:
- 15 minute intraday prices for each Friday going back in available history (LAST_PRICE)
- Daily volume (VOLUME)
	
Net Positioning

The net-positioning of the E-mini S&P 500 futures indicate the market sentiment based on whether the net position is from very long to very short.  We will download this from the Bloomberg Terminal using IMMOENCN Index, which gives a weekly series of non-commercial net-positioning data for our SP500 futures.  This data is collected on a weekly basis, so the date associated with the data point may appear on a lag.  That is, the data for 10/25/2022 may not be available until a few days after 10/25/2022.  We plot the relationship visually knowing that there is a lag in when the associated data becomes available.

2. Market data - valuation, volatility, and sentiment

S&P 500 Market Valuation

Similar to E-mini S&P 500 futures, we can also retrieve market data pertaining S&P 500 data through the Bloomberg Terminal.  Specifically, we are interested in the daily market valuation of the market (using the S&P 500 Index -- SPX Index), as measured by the Price to Earnings Ratio with the Bloomberg code: PE_RATIO.  

Market Volatility

We will use the CBOE Volatility Index, also known as VIX, to represent market expectation of volatility.  This is also available through the Bloomberg Terminal, using LAST_PRICE code against VIX Index.  We will collect daily time series for this.

Investor Sentiment

AAII provides a weekly investment sentiment index called "AAII Sentiment Survey" that measures the percentage of individual investors' future 6 month outlook for stocks.  The results is categorized into "Bullish", "Bearish", and "Neutral".  We collect this from the Bloomberg Terminal (AAIIBULL Index, AAIIBEAR Index, and AAIINEUT Index), using the LAST_PRICE code for this weekly series.

3. Macro-Economic Data

Federal Funds Rate 

Federal Funds Rate is the "interest rate depository institutions charge each other for overnight loans of funds", or the benchmark of the price of borrowing money between financial institutions.  This rate is determined by the Federal Reserve, and can be updated after each of the 8 pre-scheduled meetings by the Federal Open Market Committee (FOMC).  Banks transact with each other at this rate, and the weighted average rate for all of these is the "Effective Federal Funds Rate."  This is one of the key data points for the US economy, as a lower rate incentivizes spending and stimulates economic activity.  Higher rates, on the other hand, does the opposite, including slowing the economy and inflation.

The Effective Federal Funds Rate can be downloaded from the FRED Economic Data website, https://fred.stlouisfed.org/series/DFF.  It is a daily data series, available 7 days, and has history going back to 1955.  It can be downloaded into an Excel spreadsheet or a CSV file.

ISM Manufacturing Index 

The ISM Manufacturing Index is a monthly survey of "purchasing managers at more than 300 manufacturing firms", available on the first business day of each month.  It is a key indicator of the state of US economic activity, and its release can impact markets.  This monthly series is also available on Bloomberg Terminal, under the code "NAPMPMI Index".  It's earliest data available is on 1/31/1948.  It can be exported directly from the Terminal into an Excel or a csv file.
https://www.investopedia.com/terms/i/ism-mfg.asp

